name: flutter_dropzone
description: A drag-and-drop Flutter plugin (Web only).
version: 3.0.5
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

  flutter_dropzone_platform_interface:
    git:
      url: https://github.com/ar-io/flutter_dropzone
      ref: mastger
      path: flutter_dropzone_platform_interface
  flutter_dropzone_web:
    git:
      url: https://github.com/ar-io/flutter_dropzone
      ref: master
      path: flutter_dropzone_web

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_dropzone_web
